CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(50)                             NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    role          VARCHAR(20)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);