services:
  database:
    image: 'postgres:latest'
    container_name: 'database'
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - 'POSTGRES_USER=${DB_USERNAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'
    volumes:
      - todo:/var/lib/postgresql/data